<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-26T23:49:47 IST" name="Guru99 Banking Project" finished-at="2024-03-26T23:51:17 IST" duration-ms="90151">
    <groups>
    </groups>
    <test started-at="2024-03-26T23:49:47 IST" name="Basic Functionality" finished-at="2024-03-26T23:51:17 IST" duration-ms="90151">
      <class name="com.iNetBankingV1.testCases.DataDrivenLoginTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:49:48 IST" name="setup" finished-at="2024-03-26T23:50:28 IST" duration-ms="39985" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="openUrl()[pri:-1, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:50:28 IST" name="openUrl" finished-at="2024-03-26T23:50:40 IST" duration-ms="12039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUrl -->
        <test-method signature="TC_DDTLogin(java.lang.String,java.lang.String)[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:50:46 IST" name="TC_DDTLogin" data-provider="LoginData" finished-at="2024-03-26T23:50:58 IST" duration-ms="12372" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr561735]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mEhEnEn]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_DDTLogin -->
        <test-method signature="TC_DDTLogin(java.lang.String,java.lang.String)[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:50:58 IST" name="TC_DDTLogin" data-provider="LoginData" finished-at="2024-03-26T23:51:03 IST" duration-ms="4414" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr721736]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mEhEnJk]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed-Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed-Invalid credentials expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.iNetBankingV1.testCases.DataDrivenLoginTest.TC_DDTLogin(DataDrivenLoginTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_DDTLogin -->
        <test-method signature="TC_DDTLogin(java.lang.String,java.lang.String)[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:51:03 IST" name="TC_DDTLogin" data-provider="LoginData" finished-at="2024-03-26T23:51:08 IST" duration-ms="5469" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr561735]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mEhEnEn]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_DDTLogin -->
        <test-method signature="TC_DDTLogin(java.lang.String,java.lang.String)[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:51:08 IST" name="TC_DDTLogin" data-provider="LoginData" finished-at="2024-03-26T23:51:12 IST" duration-ms="3701" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr987038]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mOiEnEn]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed-Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed-Invalid credentials expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.iNetBankingV1.testCases.DataDrivenLoginTest.TC_DDTLogin(DataDrivenLoginTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_DDTLogin -->
        <test-method signature="TC_DDTLogin(java.lang.String,java.lang.String)[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:51:12 IST" name="TC_DDTLogin" data-provider="LoginData" finished-at="2024-03-26T23:51:16 IST" duration-ms="3924" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr121739]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mEhEnEn]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed-Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed-Invalid credentials expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.iNetBankingV1.testCases.DataDrivenLoginTest.TC_DDTLogin(DataDrivenLoginTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_DDTLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.iNetBankingV1.testCases.DataDrivenLoginTest@4c402120]" started-at="2024-03-26T23:51:16 IST" name="teardown" finished-at="2024-03-26T23:51:17 IST" duration-ms="1619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.iNetBankingV1.testCases.DataDrivenLoginTest -->
    </test> <!-- Basic Functionality -->
  </suite> <!-- Guru99 Banking Project -->
</testng-results>
